### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by githubuser872349** [DamirPorobic/kColorPicker#12]
hello I am using the current version of solus os with the budgie desktop.
i downloaded kColorPicker from the software store.
There is no shortcut.
I went to lib64 and tried both .exe files the one with .0 and the one with.0.1.6 i think, but nothing happend.
Why is that error occuring??

**Comment by DamirPorobic** [comment]
What are you actually starting? kColorPicker is just a widget, it needs to be used in an application. Have you build the example app and started it like explained here https://github.com/ksnip/kColorPicker#building-from-source?

**Comment by githubuser872349** [comment]
thank you for the answer.
i thought it is a standalone software.
so it is made for using it in another software ?

**Comment by DamirPorobic** [comment]
Yes, like it's used in kImageAnnotator. It's just a widget, like a button or so.

**Comment by githubuser872349** [comment]
thanks
