### ISSUE TITLE
Provide a tagged Release

### ISSUE THREAD

**Issue by Johnnynator** [DamirPorobic/kColorPicker#2]
It would be nice if kColorPicker had a tagged release so that Linux distributions can more easily package it (and kImageAnnotator and kSnip).

**Comment by DamirPorobic** [comment]
Hey John, kColorPicker was indeed missing the version Tag, I've set that now. kImageAnnotator and kSnip have already tags for version that that have been released:
kSnip 1.5.0, dependes on kImageAnnotator 0.0.2, depends on kColorPicker 0.0.1, those tags should be there. kSnip 1.6.0 is WIP and will depened on kImageAnnotator 0.1.0 which is also currently WIP.

Let me know if you need something else.

**Comment by Johnnynator** [comment]
Everything else seems to be fine, you should consider dumping a copy of the LGPL-2.0 License into both the kColorPicker repo and kImageAnnotator repos.

**Comment by Johnnynator** [comment]
And you have a typo in tour repos Description:
> Qt basd Color Picker with popup menu

basd -> based.

**Comment by DamirPorobic** [comment]
Thanks for the feedback, I've added the license files and fixed the typo ;)

**Comment by Johnnynator** [comment]
Happy to help :). And thx for the fast response.
