### ISSUE TITLE
Implement color picker tool (set color from image pixels)

### ISSUE THREAD

**Issue by crramirez** [DamirPorobic/kColorPicker#3]
Sometimes we need to fill an area with the same background color of the image:

![image](https://user-images.githubusercontent.com/8397379/67385824-1783f680-f594-11e9-83c0-169a9834b658.png)

**Comment by crramirez** [comment]
Yes sorry this is for ksnip

**Comment by crramirez** [comment]
It can be outside the color picker also, like in gimp

**Comment by DamirPorobic** [comment]
Anyway, ksnip does nothing with annotation, it would be part of KImageAnnotator if it were in the editor :)
But I do see it as part of the colorPicker as the color picker is responsible for selecting the color. Of course, if technically doable here.

**Comment by DamirPorobic** [comment]
Don't we have this option here 
![image](https://user-images.githubusercontent.com/12796236/82812623-ae4ec380-9e93-11ea-9b4a-9d617048e5c7.png)

**Comment by DamirPorobic** [comment]
This is already supported, closing issue.
