### ISSUE TITLE
Kcolorpicker now available in Debian (and its derivatives)

### ISSUE THREAD

**Issue by hosiet** [DamirPorobic/kColorPicker#5]
Hi, you may now find the packaged kcolorpicker library at https://tracker.debian.org/pkg/kcolorpicker . It is appearing as shared libraries and the packaging scripts are located at https://salsa.debian.org/debian/kcolorpicker . Feel free to let me know if you have any questions.

**Comment by DamirPorobic** [comment]
One question though, does the repository get automatically triggered when I push s new tag?

________________________________

**Comment by hosiet** [comment]
Not really, I (or other Debian Developers) will be manually reviewing the code before importing in this repo. However, there are monitoring infrastructures in Debian when upstream makes a new release and I will receive that info.

If you find it necessary to make updates, feel free to ping me.
