### ISSUE TITLE
bumped SONAME without name change

### ISSUE THREAD

**Issue by idamir** [DamirPorobic/kColorPicker#9]
Origin issue is described here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977649

Spectacle from KDE is unable to start after the libkimageannotator0 package updated to 0.4.0-1
When attempting to start it, it crashes with "error while loading shared libraries: libkImageAnnotator.so.0.3.2: cannot open shared object file: No such file or directory". The problem is that the new version of kimageannotator bumps
the SONAME of the shared library from libkImageAnnotator.so.0.3.2 to libkImageAnnotator.so.0.4.0. This also means that kimageannotator sets the SONAME of its shared library to the full version number, basically breaking compatibility even in patch releases.
The same issue takes place for kcolorpicker.

Please set correct soname for the library:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -56,7 +56,8 @@ set_target_properties(kColorPicker
                                          ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib
                                          LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib
                                          RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin
-                                         SOVERSION ${PROJECT_VERSION}
+                                         VERSION ${PROJECT_VERSION}
+                                         SOVERSION 0
                                          )

 install(TARGETS kColorPicker
```

**Comment by DamirPorobic** [comment]
Done.
